### ISSUE TITLE
Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by LinxHex** [kayanouriko/quantumultx-skland-auto-sign#1]
按照Readme走完步骤后，运行报错：Right side of assignment cannot be destructured
![IMG_0024](https://github.com/kayanouriko/quantumultx-skland-auto-sign/assets/92703641/0bec505f-8cc9-42c2-933d-b3b897d16f01)
请问如何解决？

**Comment by kayanouriko** [comment]
这个可能报错的地方太多了, 没账号基本不好排查_(:3
想了一下最有可能出现报错的地方, 你的森空岛明日方舟有没有绑定账号, 账号是官服还是b服.

**Comment by LinxHex** [comment]
> 这个可能报错的地方太多了, 没账号基本不好排查_(:3 想了一下最有可能出现报错的地方, 你的森空岛明日方舟有没有绑定账号, 账号是官服还是b服.

绑定了官服账号。之前没问题的，换了手机再重新弄就这样了😂

**Comment by kayanouriko** [comment]
我重现了, 森空岛新版本接口变了...
稍等一下, 我今天内修复一下.

**Comment by kayanouriko** [comment]
按 [获取脚本执行必须参数](https://github.com/kayanouriko/quantumultx-skland-auto-sign#%E8%8E%B7%E5%8F%96%E8%84%9A%E6%9C%AC%E6%89%A7%E8%A1%8C%E5%BF%85%E9%A1%BB%E5%8F%82%E6%95%B0) 步骤重新获取一下 token 可以解决问题.
脚本主体不需要更新.
